// Minimal OpenAI-compatible Chat Completions stub for local verification.
// Stands in for the GreenNode MaaS endpoint when none is available.
// Returns per-type artifact JSON whose titles start with "STUB" so we can
// confirm the model path (not the template fallback) was exercised.
import Fastify from 'fastify';

const MINIMAL: Record<string, unknown> = {
  Doc: { kind: 'Doc', eyebrow: 'STUB · MEMO', title: 'STUB Doc from model', meta: 'stub', paragraphs: ['Generated by the model stub.'] },
  Deck: { kind: 'Deck', eyebrow: 'STUB · DECK', title: 'STUB Deck from model', subtitle: 'stub', slides: [{ title: 'STUB Deck from model', isCover: true, subtitle: 'stub' }, { title: 'Detail', bullets: ['point one'] }] },
  Sheet: { kind: 'Sheet', title: 'STUB Sheet from model', columns: ['Item', 'Value'], rows: [['Alpha', 1], ['Beta', 2]] },
  Dashboard: { kind: 'Dashboard', title: 'STUB Dashboard from model', subtitle: 'stub', tiles: [{ label: 'KPI', value: '42' }], series: { label: 'trend', bars: [0.4, 0.7, 1] } },
  Report: { kind: 'Report', eyebrow: 'STUB · REPORT', title: 'STUB Report from model', asOf: 'now', stats: [{ value: '42', label: 'KPI' }], paragraphs: ['Generated by the model stub.'] },
};

function detectType(messages: { role: string; content: string }[]): string {
  const sys = messages.find((m) => m.role === 'system')?.content ?? '';
  for (const t of Object.keys(MINIMAL)) if (sys.includes(`Produce a ${t}`) || sys.includes(`given an existing ${t}`)) return t;
  return 'Doc';
}

const app = Fastify({ logger: false });
app.post('/chat/completions', async (req) => {
  const body = req.body as { messages: { role: string; content: string }[] };
  const type = detectType(body.messages);
  return {
    id: 'stub-1',
    object: 'chat.completion',
    choices: [{ index: 0, message: { role: 'assistant', content: JSON.stringify(MINIMAL[type]) }, finish_reason: 'stop' }],
  };
});

const port = Number(process.env.STUB_PORT ?? 8788);
app.listen({ port, host: '127.0.0.1' }).then(() => console.log(`[model-stub] http://127.0.0.1:${port}/chat/completions`));
