// Faithful-enough OpenAI-compatible Chat Completions stub for local verification.
// Stands in for the GreenNode MaaS endpoint. Supports BOTH non-streaming JSON
// (used by the BFF direct path) and streaming SSE (used by OpenCode's ai-sdk
// provider). Returns per-type artifact JSON whose titles start with "STUB" so we
// can confirm the model path was exercised.
import Fastify from 'fastify';

const MINIMAL: Record<string, unknown> = {
  Doc: { kind: 'Doc', eyebrow: 'STUB · MEMO', title: 'STUB Doc from model', meta: 'stub', paragraphs: ['Generated by the model stub.'] },
  Deck: { kind: 'Deck', eyebrow: 'STUB · DECK', title: 'STUB Deck from model', subtitle: 'stub', slides: [{ title: 'STUB Deck from model', isCover: true, subtitle: 'stub' }, { title: 'Detail', bullets: ['point one'] }] },
  Sheet: { kind: 'Sheet', title: 'STUB Sheet from model', columns: ['Item', 'Value'], rows: [['Alpha', 1], ['Beta', 2]] },
  Dashboard: { kind: 'Dashboard', title: 'STUB Dashboard from model', subtitle: 'stub', tiles: [{ label: 'KPI', value: '42' }], series: { label: 'trend', bars: [0.4, 0.7, 1] } },
  Report: { kind: 'Report', eyebrow: 'STUB · REPORT', title: 'STUB Report from model', asOf: 'now', stats: [{ value: '42', label: 'KPI' }], paragraphs: ['Generated by the model stub.'] },
};

const asText = (c: unknown): string =>
  typeof c === 'string' ? c : Array.isArray(c) ? c.map((p: any) => p?.text ?? '').join(' ') : '';

function detectType(messages: { role: string; content: unknown }[]): string {
  const all = messages.map((m) => asText(m.content)).join('\n');
  for (const t of Object.keys(MINIMAL)) if (all.includes(`Produce a ${t}`) || all.includes(`existing ${t}`)) return t;
  return 'Doc';
}

const app = Fastify({ logger: false });

app.get('/models', async () => ({
  object: 'list',
  data: Object.keys({ 'llama3-70b': 1, 'qwen25-72b': 1, 'mistral-large': 1 }).map((id) => ({ id, object: 'model', owned_by: 'greennode' })),
}));

app.post('/chat/completions', async (req, reply) => {
  const body = req.body as { messages?: { role: string; content: unknown }[]; stream?: boolean };
  const type = detectType(body.messages ?? []);
  const content = JSON.stringify(MINIMAL[type]);
  const id = 'stub-' + Date.now();

  if (body.stream) {
    reply.hijack();
    const raw = reply.raw;
    raw.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' });
    const chunk = (delta: unknown, finish: string | null) =>
      `data: ${JSON.stringify({ id, object: 'chat.completion.chunk', model: 'stub', choices: [{ index: 0, delta, finish_reason: finish }] })}\n\n`;
    raw.write(chunk({ role: 'assistant' }, null));
    raw.write(chunk({ content }, null));
    raw.write(chunk({}, 'stop'));
    raw.write('data: [DONE]\n\n');
    raw.end();
    return;
  }

  return {
    id,
    object: 'chat.completion',
    model: 'stub',
    choices: [{ index: 0, message: { role: 'assistant', content }, finish_reason: 'stop' }],
    usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
  };
});

const port = Number(process.env.STUB_PORT ?? 8788);
app.listen({ port, host: '127.0.0.1' }).then(() => console.log(`[model-stub] http://127.0.0.1:${port} (chat/completions + streaming)`));
